/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { HousingApplicantCreateNestedManyWithoutUsersInput } from "./HousingApplicantCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { HousingOfferingCreateNestedManyWithoutUsersInput } from "./HousingOfferingCreateNestedManyWithoutUsersInput";
import { JobApplicantCreateNestedManyWithoutUsersInput } from "./JobApplicantCreateNestedManyWithoutUsersInput";
import { JobOfferingCreateNestedManyWithoutUsersInput } from "./JobOfferingCreateNestedManyWithoutUsersInput";
@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  first_name!: string;

  @ApiProperty({
    required: false,
    type: () => HousingApplicantCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => HousingApplicantCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => HousingApplicantCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  housing_applicants?: HousingApplicantCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => HousingOfferingCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => HousingOfferingCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => HousingOfferingCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  housing_offerings?: HousingOfferingCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => JobApplicantCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => JobApplicantCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => JobApplicantCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  job_applicants?: JobApplicantCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => JobOfferingCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => JobOfferingCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => JobOfferingCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  job_offerings?: JobOfferingCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  last_name!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  location!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  telephone_number!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  user_type!: string;
}
export { UserCreateInput };
