/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { JobApplicantService } from "../jobApplicant.service";
import { JobApplicantCreateInput } from "./JobApplicantCreateInput";
import { JobApplicantWhereInput } from "./JobApplicantWhereInput";
import { JobApplicantWhereUniqueInput } from "./JobApplicantWhereUniqueInput";
import { JobApplicantFindManyArgs } from "./JobApplicantFindManyArgs";
import { JobApplicantUpdateInput } from "./JobApplicantUpdateInput";
import { JobApplicant } from "./JobApplicant";
@swagger.ApiBearerAuth()
export class JobApplicantControllerBase {
  constructor(
    protected readonly service: JobApplicantService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "JobApplicant",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: JobApplicant })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: JobApplicantCreateInput
  ): Promise<JobApplicant> {
    return await this.service.create({
      data: {
        ...data,

        job_offering_id: {
          connect: data.job_offering_id,
        },

        user_id: {
          connect: data.user_id,
        },
      },
      select: {
        id: true,

        job_offering_id: {
          select: {
            id: true,
          },
        },

        user_id: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "JobApplicant",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: [JobApplicant] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(JobApplicantFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<JobApplicant[]> {
    const args = plainToClass(JobApplicantFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,

        job_offering_id: {
          select: {
            id: true,
          },
        },

        user_id: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "JobApplicant",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: JobApplicant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: JobApplicantWhereUniqueInput
  ): Promise<JobApplicant | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,

        job_offering_id: {
          select: {
            id: true,
          },
        },

        user_id: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "JobApplicant",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: JobApplicant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: JobApplicantWhereUniqueInput,
    @common.Body() data: JobApplicantUpdateInput
  ): Promise<JobApplicant | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          job_offering_id: {
            connect: data.job_offering_id,
          },

          user_id: {
            connect: data.user_id,
          },
        },
        select: {
          id: true,

          job_offering_id: {
            select: {
              id: true,
            },
          },

          user_id: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "JobApplicant",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: JobApplicant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: JobApplicantWhereUniqueInput
  ): Promise<JobApplicant | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,

          job_offering_id: {
            select: {
              id: true,
            },
          },

          user_id: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
